# Study simple gradient policy training

In [1]:
import tensorflow as tf
import numpy as np
import gym
from gym.spaces import Discrete, Box

from IPython.core.debugger import set_trace


In [2]:
def mlp(x, sizes, activation=tf.tanh, output_activation=None):
    # Build a feedforward neural network.
    for size in sizes[:-1]:
        x = tf.layers.dense(x, units=size, activation=activation)
    return tf.layers.dense(x, units=sizes[-1], activation=output_activation)

def train(env_name='CartPole-v0', hidden_sizes=[32], lr=1e-2, 
          epochs=5, batch_size=5000, render=False):

    # make environment, check spaces, get obs / act dims
    env = gym.make(env_name)
    assert isinstance(env.observation_space, Box), \
        "This example only works for envs with continuous state spaces."
    assert isinstance(env.action_space, Discrete), \
        "This example only works for envs with discrete action spaces."

    obs_dim = env.observation_space.shape[0]
    n_acts = env.action_space.n

    # make core of policy network
    obs_ph = tf.placeholder(shape=(None, obs_dim), dtype=tf.float32)
    logits = mlp(obs_ph, sizes=hidden_sizes+[n_acts])
    print(f'logits shape: {logits.shape}')
    
    tmp = tf.multinomial(logits=logits,num_samples=1)
    print(f'multinomial shape: {tmp.shape}')
    
    # make action selection op (outputs int actions, sampled from policy)
    actions = tf.squeeze(tmp, axis=1)
    print(f'actons shape: {actions.shape}')

    # make loss function whose gradient, for the right data, is policy gradient
    weights_ph = tf.placeholder(shape=(None,), dtype=tf.float32)
    act_ph = tf.placeholder(shape=(None,), dtype=tf.int32)
    action_masks = tf.one_hot(act_ph, n_acts)
    log_probs = tf.reduce_sum(action_masks * tf.nn.log_softmax(logits), axis=1)
    loss = -tf.reduce_mean(weights_ph * log_probs)

    # make train op
    train_op = tf.train.AdamOptimizer(learning_rate=lr).minimize(loss)

    sess = tf.InteractiveSession()
    sess.run(tf.global_variables_initializer())

    # for training policy
    def train_one_epoch():
        # make some empty lists for logging.
        batch_obs = []          # for observations
        batch_acts = []         # for actions
        batch_weights = []      # for R(tau) weighting in policy gradient
        batch_rets = []         # for measuring episode returns
        batch_lens = []         # for measuring episode lengths

        # reset episode-specific variables
        obs = env.reset()       # first obs comes from starting distribution
        done = False            # signal from environment that episode is over
        ep_rews = []            # list for rewards accrued throughout ep

        # render first episode of each epoch
        finished_rendering_this_epoch = False

        # collect experience by acting in the environment with current policy
        while True:

            # rendering
            if (not finished_rendering_this_epoch) and render:
                env.render()

            # save obs
            batch_obs.append(obs.copy())

            # act in the environment
            act = sess.run(actions, {obs_ph: obs.reshape(1,-1)})[0]
            obs, rew, done, _ = env.step(act)

            # save action, reward
            batch_acts.append(act)
            ep_rews.append(rew)

            if done:
                # if episode is over, record info about episode
                ep_ret, ep_len = sum(ep_rews), len(ep_rews)
                batch_rets.append(ep_ret)
                batch_lens.append(ep_len)

                # the weight for each logprob(a|s) is R(tau)
                batch_weights += [ep_ret] * ep_len

                # reset episode-specific variables
                obs, done, ep_rews = env.reset(), False, []

                # won't render again this epoch
                finished_rendering_this_epoch = True

                # end experience loop if we have enough of it
                if len(batch_obs) > batch_size:
                    break

        # take a single policy gradient update step
        batch_loss, _ = sess.run([loss, train_op],
                                 feed_dict={
                                    obs_ph: np.array(batch_obs),
                                    act_ph: np.array(batch_acts),
                                    weights_ph: np.array(batch_weights)
                                 })
        return batch_loss, batch_rets, batch_lens

    # training loop
    for i in range(epochs):
        batch_loss, batch_rets, batch_lens = train_one_epoch()
        print('epoch: %3d \t loss: %.3f \t return: %.3f \t ep_len: %.3f'%
                (i, batch_loss, np.mean(batch_rets), np.mean(batch_lens)))

In [3]:
train(env_name='CartPole-v0', render=False, lr=1e-2)

Instructions for updating:
Use keras.layers.dense instead.
Instructions for updating:
Colocations handled automatically by placer.
logits shape: (?, 2)
Instructions for updating:
Use tf.random.categorical instead.
multinomial shape: (?, 1)
actons shape: (?,)
Instructions for updating:
Use tf.cast instead.
epoch:   0 	 loss: 30.654 	 return: 35.702 	 ep_len: 35.702
epoch:   1 	 loss: 33.808 	 return: 42.025 	 ep_len: 42.025
epoch:   2 	 loss: 33.559 	 return: 42.143 	 ep_len: 42.143
epoch:   3 	 loss: 38.145 	 return: 47.255 	 ep_len: 47.255
epoch:   4 	 loss: 42.400 	 return: 54.750 	 ep_len: 54.750


In [4]:
isess = tf.InteractiveSession()

/home/user/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py:1702: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [5]:
in_probab = np.array([[1/9.,1/4.,7/3.]])
print(in_probab.shape)
samples = tf.multinomial(logits=tf.log(in_probab), num_samples=1)
tmp = isess.run(tf.squeeze(samples, axis=1))
print(tmp.shape)

(1, 3)
(1,)


In [6]:
count = [0, 0, 0]
for _ in range(1000):
    pick = isess.run(tf.squeeze(samples, axis=1))[0]
    count[pick] += 1

print(count)

[40, 95, 865]


In [7]:
isess.close()

In [8]:
size = [32]+[2]

In [9]:
print(size[:-1])

[32]


In [10]:
print(size[-1])

2


In [11]:
isess = tf.InteractiveSession()
in_probab = np.array([[0.1, 0.2, 0.7]])
print(in_probab.shape)
samples = tf.multinomial(logits=tf.log(in_probab), num_samples=10000)
tmp = isess.run(tf.squeeze(samples))
isess.close()

print(tmp.shape)
print(tmp)

from collections import Counter
Counter(tmp)

(1, 3)
(10000,)
[2 0 2 ... 2 0 0]


Counter({2: 6950, 0: 1028, 1: 2022})

In [12]:
# work through exercise 2 solutions

import tensorflow as tf
import numpy as np

In [13]:
x = tf.constant(np.arange(5))
y = tf.constant(np.arange(5).reshape(-1,1))

In [14]:
sess = tf.InteractiveSession()
sess.run(x)
sess.run(y)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [15]:
sess.close()

In [16]:
x = np.arange(5)

In [17]:
print(x.shape)

(5,)


In [18]:
print(x.reshape(-1,1).shape)

(5, 1)


In [19]:
env = gym.make("LunarLander-v2")

In [20]:
env.observation_space

Box(8,)

In [30]:
env.action_space

Box(6,)

In [23]:
import pybulletgym

In [24]:
import gym

In [28]:
env = gym.make('HalfCheetahMuJoCoEnv-v0')

WalkerBase::__init__


In [29]:
env.reset()

options= 


array([ 0.09694638, -0.01106042,  0.078821  , -0.03235668,  0.08811393,
       -0.08623581, -0.04509367, -0.06486257,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ], dtype=float32)